import { escapeHtml } from './format';
import type { CustomerModule, ErpModule, Project, ProjectModuleConfig } from '../types/entities';

const clean = (value: string) => escapeHtml(value || '–');
export function exportProjectModules(project: Project, rows: { module: ErpModule; assignment: CustomerModule; config?: ProjectModuleConfig }[]) {
  const body = rows.map(({ module, assignment, config }) => `<tr><td><strong>${clean(module.name)}</strong><br><small>${clean(module.kategorie)}</small></td><td>${clean(module.beschreibung)}</td><td>${assignment.commercialStatus === 'vertrag' ? 'Im Vertrag enthalten' : 'Nachlizenzierung'}<br><small>${clean(assignment.offerNumber)} · ${clean(assignment.offerStatus)}</small></td><td>${clean(config?.einrichtungsstatus || 'nicht begonnen')}<br><small>${clean(config?.verantwortlicher || '')}</small></td><td>${clean(config?.einrichtungsdetails || '')}</td><td>${clean(config?.notizen || assignment.notizen)}</td></tr>`).join('');
  const html = `<!doctype html><html lang="de"><head><meta charset="utf-8"><title>${clean(project.name)} – Module</title><style>@page{size:A4 landscape;margin:14mm}body{font:10pt/1.4 Arial;color:#111}header{border-bottom:3px solid #111;margin-bottom:18px}h1{margin:0}header p{color:#555}table{width:100%;border-collapse:collapse}th,td{padding:8px;border:1px solid #aaa;text-align:left;vertical-align:top}th{background:#eee;font-size:8pt;text-transform:uppercase}small{color:#666}footer{margin-top:16px;color:#777;font-size:8pt}</style></head><body><header><h1>${clean(project.name)}</h1><p>Modulliste · ${clean(project.kunde)}</p></header><table><thead><tr><th>Modul</th><th>Globale Information</th><th>Vertrag / Angebot</th><th>Einrichtung</th><th>Projektdetails</th><th>Notizen</th></tr></thead><tbody>${body || '<tr><td colspan="6">Keine Module zugeordnet.</td></tr>'}</tbody></table><footer>Exportiert am ${clean(new Intl.DateTimeFormat('de-DE', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date()))} · Projektzentrale</footer></body></html>`;
  const url = URL.createObjectURL(new Blob([html], { type: 'text/html;charset=utf-8' }));
  const anchor = document.createElement('a'); anchor.href = url; anchor.download = `${project.name.replace(/[^a-z0-9_-]+/gi, '-')}-module.html`; document.body.appendChild(anchor); anchor.click(); anchor.remove(); URL.revokeObjectURL(url);
}
