import { useState } from 'react';
import { useDataStore } from '../../../store/dataStore';
import { exportProjectModules } from '../../../lib/moduleExport';
import type { CustomerModule, ErpModule, Project, ProjectCache, ProjectModuleConfig } from '../../../types/entities';

export default function ModuleTab({ project, data }: { project: Project; data: ProjectCache }) {
  const modules = useDataStore((s) => s.modules);
  const customerModules = useDataStore((s) => s.customerModules).filter((item) => item.kunde === project.kunde);
  const saveCustomerModule = useDataStore((s) => s.saveCustomerModule);
  const deleteCustomerModule = useDataStore((s) => s.deleteCustomerModule);
  const saveProjectModuleConfig = useDataStore((s) => s.saveProjectModuleConfig);
  const [selected, setSelected] = useState('');
  const [editing, setEditing] = useState<string | null>(null);
  const available = modules.filter((module) => !customerModules.some((item) => item.moduleId === module.id));
  const rows = customerModules.map((assignment) => ({ assignment, module: modules.find((item) => item.id === assignment.moduleId) })).filter((row): row is { assignment: CustomerModule; module: ErpModule } => !!row.module);
  async function add() { if (!selected) return; await saveCustomerModule({ moduleId: selected, kunde: project.kunde, commercialStatus: 'vertrag', offerNumber: '', offerStatus: 'kein Angebot', notizen: '' }); setSelected(''); }
  return <section className="project-modules"><div className="module-section-head"><div><span className="eyebrow">Kunde · {project.kunde || 'Ohne Kundenangabe'}</span><h3>Module</h3><p>Die Auswahl sowie Vertrags- und Angebotsdaten gelten für alle Projekte dieses Kunden. Die Einrichtung pflegst du je Projekt separat.</p></div><button className="btn secondary small" onClick={() => exportProjectModules(project, rows.map((row) => ({ ...row, config: data.moduleConfigs.find((c) => c.moduleId === row.module.id) })))}>⇩ Modulliste exportieren</button></div>
    <div className="module-add-row"><select value={selected} onChange={(e) => setSelected(e.target.value)}><option value="">Modul aus globalem Katalog wählen…</option>{available.map((module) => <option value={module.id} key={module.id}>{module.name}</option>)}</select><button className="btn small" disabled={!selected || !project.kunde} onClick={add}>Hinzufügen</button>{modules.length === 0 && <small>Module zuerst unter Einstellungen anlegen.</small>}</div>
    {rows.length === 0 ? <div className="empty-state"><h3>Keine Module zugeordnet</h3><div>Wähle die für diesen Kunden relevanten Module aus.</div></div> : <div className="project-module-list">{rows.map(({ module, assignment }) => { const config = data.moduleConfigs.find((item) => item.moduleId === module.id); return <article className="module-project-card" key={module.id}><div className="module-project-summary"><div><span>{module.kategorie || 'ERP-Modul'}</span><h4>{module.name}</h4><p>{module.beschreibung}</p></div><div className="module-badges"><b>{assignment.commercialStatus === 'vertrag' ? 'Im Vertrag' : 'Nachlizenzierung'}</b><em>{config?.einrichtungsstatus || 'nicht begonnen'}</em></div></div>{assignment.commercialStatus === 'nachlizenzierung' && <div className="module-offer-line">Angebot: <strong>{assignment.offerNumber || 'ohne Nummer'}</strong> · {assignment.offerStatus}</div>}<div className="actions"><button className="btn secondary small" onClick={() => setEditing(module.id)}>Details & Einrichtung</button><button className="icon-btn" onClick={() => deleteCustomerModule(project.kunde, module.id)}>Beim Kunden entfernen</button></div>{editing === module.id && <ModuleProjectEditor assignment={assignment} config={config} projectId={project.id} onSave={async (a, c) => { await saveCustomerModule(a); await saveProjectModuleConfig(project.id, c); setEditing(null); }} onClose={() => setEditing(null)} />}</article>; })}</div>}
  </section>;
}

function ModuleProjectEditor({ assignment, config, projectId, onSave, onClose }: { assignment: CustomerModule; config?: ProjectModuleConfig; projectId: string; onSave: (a: CustomerModule, c: ProjectModuleConfig) => Promise<void>; onClose: () => void }) {
  const [a, setA] = useState(assignment); const [c, setC] = useState<ProjectModuleConfig>(config || { moduleId: assignment.moduleId, einrichtungsstatus: 'nicht begonnen', verantwortlicher: '', einrichtungsdetails: '', notizen: '', updatedAt: '' }); void projectId;
  return <div className="task-edit-overlay" role="dialog" aria-modal="true"><div className="task-edit-dialog"><div className="task-edit-dialog-head"><div><span>Kundenweit & projektspezifisch</span><strong>Moduldetails bearbeiten</strong></div></div><h4>Kundenweite Vertragsdaten</h4><div className="field-grid"><div className="field"><label>Lizenzierung</label><select value={a.commercialStatus} onChange={(e) => setA({ ...a, commercialStatus: e.target.value as CustomerModule['commercialStatus'] })}><option value="vertrag">Im Vertrag enthalten</option><option value="nachlizenzierung">Nachlizenzierung</option></select></div>{a.commercialStatus === 'nachlizenzierung' && <><div className="field"><label>Angebotsnummer</label><input value={a.offerNumber} onChange={(e) => setA({ ...a, offerNumber: e.target.value })} /></div><div className="field"><label>Angebotsstatus</label><select value={a.offerStatus} onChange={(e) => setA({ ...a, offerStatus: e.target.value as CustomerModule['offerStatus'] })}>{['kein Angebot','Entwurf','versendet','angenommen','abgelehnt'].map((s) => <option key={s}>{s}</option>)}</select></div></>}</div><div className="field"><label>Kundenweite Notiz</label><textarea value={a.notizen} onChange={(e) => setA({ ...a, notizen: e.target.value })} /></div><h4>Einrichtung nur in diesem Projekt</h4><div className="field-grid"><div className="field"><label>Einrichtungsstatus</label><select value={c.einrichtungsstatus} onChange={(e) => setC({ ...c, einrichtungsstatus: e.target.value as ProjectModuleConfig['einrichtungsstatus'] })}>{['nicht begonnen','in Arbeit','eingerichtet','nicht relevant'].map((s) => <option key={s}>{s}</option>)}</select></div><div className="field"><label>Verantwortlicher</label><input value={c.verantwortlicher} onChange={(e) => setC({ ...c, verantwortlicher: e.target.value })} /></div></div><div className="field"><label>Einrichtungsdetails</label><textarea rows={4} value={c.einrichtungsdetails} onChange={(e) => setC({ ...c, einrichtungsdetails: e.target.value })} /></div><div className="field"><label>Projektnotizen</label><textarea value={c.notizen} onChange={(e) => setC({ ...c, notizen: e.target.value })} /></div><div className="btn-row"><button className="btn" onClick={() => onSave(a, { ...c, updatedAt: new Date().toISOString() })}>Speichern</button><button className="btn secondary" onClick={onClose}>Abbrechen</button></div></div></div>;
}
