import { isoWeekInfo } from '../../lib/analytics';
import { formatDuration } from '../../lib/timeTracking';
import { isWorkday, localDateKey, type WorkdayOverrides } from '../../lib/workdays';
import type { Project, TimeEntry } from '../../types/entities';

function weekKey(value: string | Date) { const info = isoWeekInfo(value instanceof Date ? value.toISOString() : value); return `${info.year}-KW${String(info.week).padStart(2, '0')}`; }

export default function TimeAnalyticsOverview({ entries, projects = [], workdayOverrides, heading = 'Zeitauswertung' }: { entries: TimeEntry[]; projects?: Project[]; workdayOverrides: WorkdayOverrides; heading?: string }) {
  const daily = new Map<string, number>(); const weekly = new Map<string, number>();
  entries.forEach((entry) => { const day = localDateKey(new Date(entry.startedAt)); daily.set(day, (daily.get(day) || 0) + entry.durationMinutes); const week = weekKey(entry.startedAt); weekly.set(week, (weekly.get(week) || 0) + entry.durationMinutes); });
  const workdays: { key: string; date: Date; minutes: number }[] = []; const cursor = new Date(); cursor.setHours(12, 0, 0, 0);
  while (workdays.length < 15) { if (isWorkday(cursor, workdayOverrides)) { const key = localDateKey(cursor); workdays.push({ key, date: new Date(cursor), minutes: daily.get(key) || 0 }); } cursor.setDate(cursor.getDate() - 1); }
  const weeks: { key: string; minutes: number }[] = []; const weekCursor = new Date(); weekCursor.setHours(12, 0, 0, 0);
  while (weeks.length < 12) { const key = weekKey(weekCursor); if (!weeks.some((item) => item.key === key)) weeks.push({ key, minutes: weekly.get(key) || 0 }); weekCursor.setDate(weekCursor.getDate() - 7); }
  const today = daily.get(localDateKey(new Date())) || 0; const currentWeek = weekly.get(weekKey(new Date())) || 0; const total = entries.reduce((sum, entry) => sum + entry.durationMinutes, 0); const activeDays = [...daily.entries()].filter(([key, minutes]) => minutes > 0 && isWorkday(new Date(`${key}T12:00:00`), workdayOverrides)).map(([, minutes]) => minutes); const average = activeDays.length ? activeDays.reduce((sum, minutes) => sum + minutes, 0) / activeDays.length : 0; const maxDay = Math.max(1, ...workdays.map((item) => item.minutes)); const maxWeek = Math.max(1, ...weeks.map((item) => item.minutes));
  const projectRows = projects.map((project) => ({ project, minutes: entries.filter((entry) => entry.projectId === project.id).reduce((sum, entry) => sum + entry.durationMinutes, 0) })).filter((row) => row.minutes > 0).sort((a, b) => b.minutes - a.minutes);
  return <section className="time-analytics-overview"><div className="analytics-section-intro"><div className="analytics-scope-label">Arbeitszeit</div><h3>{heading}</h3><p>Auswertung nach vollständigem Buchungsdatum, Arbeitstag und ISO-Kalenderwoche.</p></div><div className="analytics-kpi-grid"><article><strong>{formatDuration(today)}</strong><span>Heute</span><small>aktueller Arbeitstag</small></article><article><strong>{formatDuration(currentWeek)}</strong><span>Aktuelle KW</span><small>{weekKey(new Date())}</small></article><article><strong>{formatDuration(total)}</strong><span>Gesamtzeit</span><small>{entries.length} Buchungen</small></article><article><strong>{formatDuration(average)}</strong><span>Ø pro Arbeitstag</span><small>{activeDays.length} Tage mit Buchung</small></article></div><div className="time-analysis-columns"><article className="analytics-detail-card"><div className="analytics-block-head"><div><h3>Nach Arbeitstag</h3><p>Die letzten 15 konfigurierten Arbeitstage.</p></div></div><div className="time-period-list">{workdays.map((item) => <div key={item.key}><span>{new Intl.DateTimeFormat('de-DE', { weekday: 'short', day: '2-digit', month: '2-digit', year: 'numeric' }).format(item.date)}</span><i><b style={{ width: `${item.minutes / maxDay * 100}%` }} /></i><strong>{formatDuration(item.minutes)}</strong></div>)}</div></article><article className="analytics-detail-card"><div className="analytics-block-head"><div><h3>Nach Kalenderwoche</h3><p>Die letzten zwölf ISO-Kalenderwochen.</p></div></div><div className="time-period-list">{weeks.map((item) => <div key={item.key}><span>{item.key}</span><i><b style={{ width: `${item.minutes / maxWeek * 100}%` }} /></i><strong>{formatDuration(item.minutes)}</strong></div>)}</div></article></div>{projectRows.length > 0 && <div className="analytics-table-wrap time-project-table"><table className="an-table"><thead><tr><th>Projekt</th><th>Kunde</th><th>Erfasste Zeit</th></tr></thead><tbody>{projectRows.map(({ project, minutes }) => <tr key={project.id}><td><strong>{project.name}</strong></td><td>{project.kunde || '–'}</td><td>{formatDuration(minutes)}</td></tr>)}</tbody></table></div>}</section>;
}
