import { useState } from 'react';
import { useDataStore } from '../../store/dataStore';
import { useModalStore } from '../../store/modalStore';
import { uid } from '../../lib/format';
import type { ErpModule } from '../../types/entities';
import { useDragReorder } from '../../hooks/useDragReorder';

const emptyModule = (parentId: string | null): ErpModule => ({ id: uid(), parentId, name: '', beschreibung: '', notizen: '', createdAt: new Date().toISOString(), sortIndex: 0 });

export default function ModuleSettings() {
  const modules = useDataStore((s) => s.modules); const saveModule = useDataStore((s) => s.saveModule); const deleteModule = useDataStore((s) => s.deleteModule); const reorderModule = useDataStore((s) => s.reorderModule); const confirm = useModalStore((s) => s.confirm); const [editing, setEditing] = useState<ErpModule | null>(null);
  const parents = modules.filter((module) => !module.parentId).sort((a, b) => a.sortIndex - b.sortIndex);
  const { getItemProps } = useDragReorder({ getGroupKey: (id) => modules.find((module) => module.id === id)?.parentId || '_root', onDrop: reorderModule });
  async function remove(module: ErpModule) { const children = modules.filter((item) => item.parentId === module.id); const suffix = children.length ? ` sowie ${children.length} enthaltene${children.length === 1 ? 's Modul' : ' Module'}` : ''; if (await confirm(`${module.parentId ? 'Modul' : 'Obermodul'} „${module.name}“${suffix} global löschen? Bestehende Kunden- und Projektzuordnungen werden ebenfalls entfernt.`)) await deleteModule(module.id); }
  return <section id="module-settings" className="settings-validation">
    <div className="module-section-head"><div><h3>Globale Modulverwaltung</h3><p>Obermodule strukturieren den Katalog. Die darin enthaltenen Module können Kunden und Projekten zugeordnet werden.</p></div><button className="btn small" onClick={() => setEditing(emptyModule(null))}>+ Obermodul</button></div>
    {parents.length === 0 ? <div className="empty-state"><h3>Noch keine Obermodule</h3><div>Lege beispielsweise das Obermodul „Verkauf“ an.</div></div> : <div className="module-hierarchy">{parents.map((parent) => { const children = modules.filter((module) => module.parentId === parent.id).sort((a, b) => a.sortIndex - b.sortIndex); return <section className="module-parent-card" key={parent.id}><header {...getItemProps(parent.id)}><div><span>↕ Ziehen · Obermodul</span><h4>{parent.name}</h4>{parent.beschreibung && <p>{parent.beschreibung}</p>}</div><div className="actions"><button className="btn small" onClick={() => setEditing(emptyModule(parent.id))}>+ Enthaltenes Modul</button><button className="btn secondary small" onClick={() => setEditing(parent)}>Bearbeiten</button><button className="icon-btn" onClick={() => remove(parent)}>Löschen</button></div></header><div className="module-child-list">{children.length === 0 ? <div className="module-child-empty">Noch keine enthaltenen Module.</div> : children.map((module) => <article key={module.id} {...getItemProps(module.id)}><div><span className="module-drag-hint">↕</span><strong>{module.name}</strong>{module.beschreibung && <small>{module.beschreibung}</small>}</div><div className="actions"><button className="icon-btn edit" onClick={() => setEditing(module)}>Bearbeiten</button><button className="icon-btn" onClick={() => remove(module)}>Löschen</button></div></article>)}</div></section>; })}</div>}
    {editing && <ModuleEditor module={editing} parentName={editing.parentId ? modules.find((item) => item.id === editing.parentId)?.name : undefined} onClose={() => setEditing(null)} onSave={async (module) => { await saveModule(module); setEditing(null); }} />}
  </section>;
}

function ModuleEditor({ module, parentName, onSave, onClose }: { module: ErpModule; parentName?: string; onSave: (module: ErpModule) => Promise<void>; onClose: () => void }) {
  const [value, setValue] = useState(module); const child = !!module.parentId; const field = (key: 'name' | 'beschreibung' | 'notizen', next: string) => setValue((current) => ({ ...current, [key]: next }));
  return <div className="task-edit-overlay" role="dialog" aria-modal="true"><div className="task-edit-dialog"><div className="task-edit-dialog-head"><div><span>{child ? `Enthalten in ${parentName || 'Obermodul'}` : 'Katalogstruktur'}</span><strong>{module.name ? `${child ? 'Modul' : 'Obermodul'} bearbeiten` : `${child ? 'Enthaltenes Modul' : 'Obermodul'} anlegen`}</strong></div></div><div className="field"><label>Name *</label><input autoFocus value={value.name} onChange={(e) => field('name', e.target.value)} placeholder={child ? 'z. B. EDI INVOICE REWE' : 'z. B. Verkauf'} /></div><div className="field"><label>Beschreibung</label><textarea rows={4} value={value.beschreibung} onChange={(e) => field('beschreibung', e.target.value)} placeholder={child ? 'Generelle Informationen zu diesem Modul' : 'Optionaler Überblick zum Obermodul'} /></div><div className="field"><label>Interne Notizen</label><textarea rows={3} value={value.notizen} onChange={(e) => field('notizen', e.target.value)} /></div><div className="btn-row"><button className="btn" disabled={!value.name.trim()} onClick={() => onSave({ ...value, name: value.name.trim() })}>Speichern</button><button className="btn secondary" onClick={onClose}>Abbrechen</button></div></div></div>;
}
